#!/bin/sh
### BEGIN INIT INFO
# Provides:          home-server
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       home-server application
### END INIT INFO

WORKING_DIR=/home/pi/home-server
SERVICE_NAME=home-server
SCRIPT=start-home-server.sh
RUNAS=pi

PIDFILE=${WORKING_DIR}/${SERVICE_NAME}.pid
LOGFILE=${WORKING_DIR}/${SERVICE_NAME}.log

start() {
  if [ -f ${PIDFILE} ] && kill -0 $(cat ${PIDFILE}); then
    echo "Service $SERVICE_NAME already running" >&2
    return 1
  fi
  echo "Starting service $SERVICE_NAME" >&2
  local CMD="$WORKING_DIR/$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" ${RUNAS} > "$PIDFILE"
  echo "Service $SERVICE_NAME started" >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo "Service $SERVICE_NAME not running" >&2
    return 1
  fi
  echo "Stopping service $SERVICE_NAME" >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo "Service $SERVICE_NAME stopped" >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
