CREATE USER IF NOT EXISTS "SA" SALT 'f0b71dc6698ee5a6' HASH '5aa505c04eab537e7c3d86dd483c7d5e9af46ddc0703c0d76243dde20466532c' ADMIN;

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1;

CREATE SEQUENCE ENERGIECONTRACT_SEQ START WITH 1;
CREATE CACHED TABLE ENERGIECONTRACT
(
    ID                            BIGINT DEFAULT NEXT VALUE FOR ENERGIECONTRACT_SEQ NOT NULL NULL_TO_DEFAULT SEQUENCE ENERGIECONTRACT_SEQ,
    GAS_PER_KUUB                  DECIMAL(7, 6),
    LEVERANCIER                   VARCHAR(255),
    STROOM_PER_KWH_DAL_TARIEF     DECIMAL(7, 6),
    STROOM_PER_KWH_NORMAAL_TARIEF DECIMAL(7, 6)                                     NOT NULL,
    VALID_FROM                    DATE                                              NOT NULL,
    VALID_TO                      DATE,
    REMARK                        VARCHAR(2048)
);
ALTER TABLE ENERGIECONTRACT
    ADD CONSTRAINT PK_ENERGIECONTRACT PRIMARY KEY (ID);

CREATE SEQUENCE METERSTAND_SEQ START WITH 1;
CREATE TABLE METERSTAND
(
    ID                      BIGINT DEFAULT NEXT VALUE FOR METERSTAND_SEQ NOT NULL NULL_TO_DEFAULT SEQUENCE METERSTAND_SEQ,
    GAS                     DECIMAL(8, 3)                                NOT NULL,
    STROOM_TARIEF1          DECIMAL(8, 3)                                NOT NULL,
    STROOM_TARIEF2          DECIMAL(8, 3)                                NOT NULL,
    STROOM_TARIEF_INDICATOR SMALLINT                                     NOT NULL,
    DATE_TIME               TIMESTAMP                                    NOT NULL
);
CREATE INDEX METERSTAND_DATE_TIME ON METERSTAND (DATE_TIME);

CREATE SEQUENCE MINDERGASNL_SETTINGS_SEQ START WITH 1;
CREATE TABLE MINDERGASNL_SETTINGS
(
    ID                   BIGINT DEFAULT NEXT VALUE FOR MINDERGASNL_SETTINGS_SEQ NOT NULL NULL_TO_DEFAULT SEQUENCE MINDERGASNL_SETTINGS_SEQ,
    AUTHENTICATIETOKEN   VARCHAR(255),
    AUTOMATISCH_UPLOADEN BOOLEAN                                                NOT NULL
);
ALTER TABLE MINDERGASNL_SETTINGS
    ADD CONSTRAINT PK_MINDERGASNL_SETTINGS PRIMARY KEY (ID);

CREATE SEQUENCE OPGENOMEN_VERMOGEN_SEQ START WITH 1;
CREATE TABLE OPGENOMEN_VERMOGEN
(
    ID               BIGINT DEFAULT NEXT VALUE FOR OPGENOMEN_VERMOGEN_SEQ NOT NULL NULL_TO_DEFAULT SEQUENCE OPGENOMEN_VERMOGEN_SEQ,
    DATUMTIJD        TIMESTAMP                                            NOT NULL,
    TARIEF_INDICATOR SMALLINT                                             NOT NULL,
    WATT             INTEGER                                              NOT NULL
);
ALTER TABLE OPGENOMEN_VERMOGEN
    ADD CONSTRAINT PK_OPGENOMEN_VERMOGEN PRIMARY KEY (ID);
ALTER TABLE OPGENOMEN_VERMOGEN
    ADD CONSTRAINT UK_OPGENOMEN_VERMOGEN_DATUMTIJD UNIQUE (DATUMTIJD);

CREATE SEQUENCE KLIMAAT_SENSOR_ID_SEQ START WITH 1;
CREATE CACHED TABLE KLIMAAT_SENSOR
(
    ID           SMALLINT DEFAULT NEXT VALUE FOR KLIMAAT_SENSOR_ID_SEQ NOT NULL NULL_TO_DEFAULT SEQUENCE KLIMAAT_SENSOR_ID_SEQ,
    CODE         VARCHAR(255)                                          NOT NULL,
    OMSCHRIJVING VARCHAR(255)
);
ALTER TABLE KLIMAAT_SENSOR
    ADD CONSTRAINT PK_KLIMAAT_SENSOR PRIMARY KEY (ID);
ALTER TABLE KLIMAAT_SENSOR
    ADD CONSTRAINT UK_KLIMAAT_SENSOR_CODE UNIQUE (CODE);

CREATE SEQUENCE KLIMAAT_SEQ START WITH 1;
CREATE TABLE KLIMAAT
(
    ID                BIGINT DEFAULT NEXT VALUE FOR KLIMAAT_SEQ NOT NULL NULL_TO_DEFAULT SEQUENCE KLIMAAT_SEQ,
    DATUMTIJD         TIMESTAMP,
    LUCHTVOCHTIGHEID  DECIMAL(4, 1),
    TEMPERATUUR       DECIMAL(4, 2),
    KLIMAAT_SENSOR_ID SMALLINT                                  NOT NULL,
    DATUM             DATE
);
ALTER TABLE KLIMAAT
    ADD CONSTRAINT PK_KLIMAAT PRIMARY KEY (ID);
ALTER TABLE KLIMAAT
    ADD CONSTRAINT FK_KLIMAAT_KLIMAAT_SENSOR_ID_KLIMAAT_SENSOR_ID FOREIGN KEY (KLIMAAT_SENSOR_ID) REFERENCES KLIMAAT_SENSOR (ID) NOCHECK;
CREATE INDEX IDX_KLIMAAT_DATUM ON KLIMAAT (DATUM);
