###
POST http://localhost:8080/api/slimmemeter
Content-Type: application/json
Authorization: Basic home home

{
  "datumtijd": "{{$isoTimestamp}}",
  "stroomOpgenomenVermogenInWatt": 1234,
  "stroomTarief1": 5.003,
  "stroomTarief2": 10.004,
  "stroomTariefIndicator": 1,
  "gas": 0.128,
  "meterIdentificatieStroom": "ELEC-20260706",
  "meterIdentificatieGas": "GAS-20260706",
  "voltageL1": 229,
  "voltageL2": 231,
  "voltageL3": 230,
  "directGeleverdVermogenL1InWatt": 410,
  "directGeleverdVermogenL2InWatt": 405,
  "directGeleverdVermogenL3InWatt": 419,
}
